version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: accountdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  backend:
    build: ./backend  # FastAPI / Django REST
    depends_on:
      - postgres
      - redis
      - elasticsearch
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend  # React hoặc Vue
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
  esdata:
