version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: leakdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    volumes:
      - ./patterns:/app/patterns
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  crawler:
    build:
      context: ./crawler
    container_name: crawler
    restart: always
    volumes:
      - ./patterns:/app/patterns
      - ./crawler/leak_sample.txt:/app/leak_sample.txt
    depends_on:
      - elasticsearch

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
  esdata:
