services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://backend:8001
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./patterns:/app/patterns
    depends_on:
      - db
      - elasticsearch

  crawler:
    build:
      context: ./crawler
    volumes:
      - /mnt/hgfs/sharevm/:/data         # Mount thư mục chứa các file txt
      - ./patterns:/app/patterns         # Mount pattern JSON
    env_file:
      - .env
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
 
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
  esdata:
